### ISSUE TITLE
After Call is Slightly Off

### ISSUE THREAD

**Issue by shawmona** [GaryRobinson/B6TimeClock#5]
After call Earn Multiplier is showing up at 1 min 59 seconds for a 1 hr shift. It should be 2 min. I think if we extend the decimal out a few more places and round it up, this will fix the issue.

**Comment by GaryRobinson** [comment]
fixed in build 4. Yeah it helps to set the ratio to 0.033334 instead of 0.033333, but I also had a slight rounding issue
